apiVersion: "descheduler/v1alpha2"
kind: DeschedulerPolicy
metadata:
  name: comprehensive-descheduler-policy
  namespace: kube-system
profiles:
  - name: WorkloadAwareProfile
    pluginConfig:
    - name: "RemoveDuplicates"
      args:
        # Exclude StatefulSets, DaemonSets, and CronJobs from duplicate removal
        # as they have specific placement requirements
        excludeOwnerKinds:
          - "StatefulSet"
          - "DaemonSet"
          - "Job"  # This protects CronJob-created Jobs
        namespaces:
          exclude:
            - kube-system
            - kube-public
    - name: "LowNodeUtilization"
      args:
        thresholds:
          cpu: 20
          memory: 20
          pods: 20
        targetThresholds:
          cpu: 50
          memory: 50
          pods: 50
        # Don't evict DaemonSet, StatefulSet, or CronJob pods
        evictableNamespaces:
          exclude: 
            - kube-system
            - kube-public
        excludeOwnerKinds:
          - "StatefulSet"
          - "DaemonSet"
          - "Job"  # Protects CronJob pods
        # Preserve StatefulSet and DaemonSet pods
        priorityThreshold:
          value: 10000
    - name: "RemovePodsHavingTooManyRestarts"
      args:
        podRestartThreshold: 3
        includingInitContainers: true
        # Apply to all workload types but be careful with StatefulSets and CronJobs
        excludeOwnerKinds:
          - "StatefulSet"  # StatefulSets need careful restart handling
          - "Job"  # CronJob pods might restart intentionally
        namespaces:
          exclude:
            - kube-system
    - name: "RemovePodsViolatingNodeTaints"
      args:
        # This helps with node maintenance while respecting DaemonSets
        excludeOwnerKinds:
          - "DaemonSet"  # DaemonSets often need to tolerate taints
    plugins:
      deschedule:
        enabled:
          - "RemoveDuplicates"
          - "LowNodeUtilization"
          - "RemovePodsHavingTooManyRestarts"
          - "RemovePodsViolatingNodeTaints"
      balance:
        enabled:
          - "LowNodeUtilization"
