replicas: 1
leaderElection:
  enabled: true
kind: Deployment

deschedulerPolicyAPIVersion: "descheduler/v1alpha2"
deschedulerPolicy:
  profiles:
    - name: ExcludeOwnerProfile
      pluginConfig:
      - name: "RemoveDuplicates"
        args:
          excludeOwnerKinds:
            - "StatefulSet"
            - "DaemonSet"
            - "Job"
          namespaces:
            exclude: 
              - "kube-system"
              - "kube-public"
              - "kube-node-lease"
      plugins:
        balance:
          enabled:
            - "RemoveDuplicates"

evictDaemonSetPods: false
evictSystemCriticalPods: false
evictLocalStoragePods: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
