replicas: 1
leaderElection:
  enabled: true
kind: Deployment

deschedulerPolicyAPIVersion: "descheduler/v1alpha2"
deschedulerPolicy:
  profiles:
    - name: NamespaceBasedProfile
      pluginConfig:
      - name: "RemoveDuplicates"
        args:
          namespaces:
            exclude: 
              - "kube-system"
              - "kube-public"
              - "kube-node-lease"
      - name: "LowNodeUtilization"
        args:
          thresholds:
            cpu: 20
            memory: 20
            pods: 20
          targetThresholds:
            cpu: 50
            memory: 50
            pods: 50
          evictableNamespaces:
            exclude: 
              - "kube-system"
              - "kube-public"
              - "kube-node-lease"
      plugins:
        balance:
          enabled:
            - "RemoveDuplicates"
            - "LowNodeUtilization"

evictDaemonSetPods: false
evictSystemCriticalPods: false
evictLocalStoragePods: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
