replicas: 3
leaderElection:
  enabled: true
kind: Deployment

deschedulerPolicyAPIVersion: "descheduler/v1alpha2"
deschedulerPolicy:
  profiles:
    - name: ProfileWithDefaultEvictor
      pluginConfig:
      - name: "DefaultEvictor"
        args:
          evictDaemonSetPods: false
          evictSystemCriticalPods: false
          evictLocalStoragePods: false
          nodeFit: true
      - name: "RemoveDuplicates"
        args:
          namespaces:
            exclude: ["kube-system", "kube-public", "kube-node-lease"]
      - name: "LowNodeUtilization"
        args:
          thresholds:
            cpu: 20
            memory: 20
            pods: 20
          targetThresholds:
            cpu: 50
            memory: 50
            pods: 50
          evictableNamespaces:
            exclude: ["kube-system", "kube-public", "kube-node-lease"]
      - name: "RemovePodsHavingTooManyRestarts"
        args:
          podRestartThreshold: 3
          includingInitContainers: true
          namespaces:
            exclude: ["kube-system", "kube-public", "kube-node-lease"]
      plugins:
        filter:
          enabled:
            - "DefaultEvictor"
        deschedule:
          enabled:
            - "RemovePodsHavingTooManyRestarts"
        balance:
          enabled:
            - "RemoveDuplicates"
            - "LowNodeUtilization"

# Resource limits for the descheduler itself
resources:
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi
