replicas: 1
leaderElection:
  enabled: true
kind: Deployment

deschedulerPolicyAPIVersion: "descheduler/v1alpha2"
deschedulerPolicy:
  profiles:
    - name: RemoveDuplicates
      pluginConfig:
      - name: "RemoveDuplicates"
      plugins:
        balance:
          enabled:
            - "RemoveDuplicates"
    - name: ToManyRestartsProfile
      pluginConfig:
      - name: "RemovePodsHavingTooManyRestarts"
        args:
          podRestartThreshold: 5
          includingInitContainers: true
      plugins:
        deschedule:
          enabled:
            - "RemovePodsHavingTooManyRestarts"
evictDaemonSetPods: false
evictSystemCriticalPods: false
evictLocalStoragePods: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
