apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-anti-affinity
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: descheduler/v1alpha2
    kind: DeschedulerPolicy
    profiles:
      - name: AntiAffinityProfile
        pluginConfig:
          - name: DefaultEvictor
          - name: RemovePodsViolatingInterPodAntiAffinity
        plugins:
          deschedule:
            enabled:
              - RemovePodsViolatingInterPodAntiAffinity
