apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: ProfileName
    pluginConfig:
    - name: "LowNodeUtilization"
      args:
        thresholds:
          "cpu" : 20
          "memory": 20
          "pods": 20
        targetThresholds:
          "cpu" : 50
          "memory": 50
          "pods": 50
        # metricsUtilization:
        #   source: Prometheus
        #   prometheus:
        #     query: instance:node_cpu:rate:sum
        evictionLimits:
          node: 5
    plugins:
      balance:
        enabled:
          - "LowNodeUtilization"